---
title: "Introduction to eaflood"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to eaflood}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(eaflood)
library(sf)
library(tmap)
library(tibble)
library(ggplot2)
library(lubridate)
library(dplyr)
```

# Get flood warnings

```{r}
flood_warnings <- get_flood_warnings()
flood_warnings %>% 
  tibble()

flood_warning_polygons <- polygons_as_sf(flood_warnings$floodArea$polygon)
flood_warning_polygons$severity <- flood_warnings$severity


flood_warning_polygons <- flood_warning_polygons[st_is_valid(flood_warning_polygons), ]
st_is_valid(flood_warning_polygons)

tmap_mode("view")

tm_basemap() +
  tm_shape(flood_warning_polygons) +
  tm_polygons(col = "severity", alpha = 0.5)
```

# Flood areas

```{r}
flood_areas <- get_flood_areas(lat = 50.35611122908188, 
                               lon = -4.455208546257289, 
                               dist = 25)

flood_areas %>% 
  tibble()

flood_areas_polygons <- polygons_as_sf(flood_areas$polygon) %>% 
  st_make_valid()

flood_areas_polygons <- flood_areas_polygons[st_is_valid(flood_areas_polygons), ]

tm_basemap() +
  tm_shape(flood_areas_polygons) +
  tm_polygons(alpha = 0.5)
```

# Get stations

```{r}
stations <- get_stations()
stations %>% 
  tibble()
```

# Get measures

```{r}
measures <- get_measures()
measures %>% 
  tibble()

measures %>% 
  group_by(stationReference) %>% 
  summarise(count = n()) %>% 
  arrange(-count)
```

# Get readings

```{r}
readings <- get_readings(station = "3210TH")
readings %>% 
    tibble()

readings %>% 
  ggplot(aes(x = dateTime, value)) + 
  geom_line() + 
  facet_wrap(~measure, ncol = 1, scales = "free_y")
```

```{r}
readings_measure <- get_readings(measure = "L0607-level-stage-i-15_min-m")

readings_measure %>% 
  ggplot(aes(dateTime, value)) + geom_line()
```

